### PR TITLE
Resolve premature controller initialization

### LINKED ISSUE #206: Premature controller initialization
This is a follow up to zagitta/ur_modern_driver#29.

There is a potential race condition in the current driver where _sometimes_ the ros_control controllers are initialized before the joint handles contain proper information about the current robot position. This in turn can (depending on the specific controller) produce very fast and unexpected motions towards whichever garbage is found in the uninitialized handle's position memory locations. This usually happens when the controllers are spawned immediately after starting the driver, which is the default behavior when using the provided `urX_ros_control.launch` launchfiles.

I think I tracked down the problem to [this line](https://github.com/Zagitta/ur_modern_driver/pull/6/commits/6b96679047dff29acce81ccc4ef2a75bc24336b4#diff-57fa10aca32f119308fe448ef7093535R108) in zagitta/ur_modern_driver#6. Calling `ROSController::update` on consumer timeouts in turn calls `ControllerManager::update`, which potentially starts controllers if requested to do so, even if no RT packets from the robot have been yet received. I'd like to do more testing to see whether this has other side effects, but I can confirm that removing [this controller update](https://github.com/ros-industrial/ur_modern_driver/blob/3f1a5faae32fb7962db381497425a90cff52b34e/src/ros/controller.cpp#L114) removes this issue for me.

According to the [commit message](https://github.com/Zagitta/ur_modern_driver/pull/6/commits/6b96679047dff29acce81ccc4ef2a75bc24336b4) by @v4hn, _The controllers need to update at a rate of *at least* 125Hz_, but there's no further evidence for this affirmation. I'm not sure I agree with it and would suggest removing that call altogether, but I will gladly stand corrected.

Thoughts?

### PR DESCRIPTION
**Pull request by miguelprada**
In my (admittedly limited) tests this resolves #206.

It partially reverts the changes in zagitta/ur_modern_driver#6, in particular the code that ensures the controllers are updated at a minimum rate of 125Hz.

### CODE REVIEW

**Comment by miguelprada** [comment]
I reverted the original commit in this PR and replaced it with a different solution to the issue. It basically avoids calling `ControllerManager::update` (and therefore avoids starting controllers) until at least one RTPacket has been received.

Feel free to squash merge if you're happy with the final result.

File: src/ros/controller.cpp [hunk 1]
```diff
@@ -79,6 +80,7 @@ void ROSController::reset()
 
 void ROSController::read(RTShared& packet)
 {
+  state_initialized_ = true;
```
Comment (v4hn) [inline src/ros/controller.cpp]: logically this belongs *behind* the update calls below.

**Comment by AndyZe** [comment]
Works great for me.

**Comment by miguelprada** [comment]
Ping @gavanderhoorn, @ipa-nhg. Any chance you can review this?

Not sure why the tests are marked yellow here, since they [show as passed in Travis CI](https://travis-ci.org/ros-industrial/ur_modern_driver/builds/445186718?utm_source=github_status&utm_medium=notification).

**Comment by gavanderhoorn** [comment]
I've restarted the build.

Travis can be a bit strange sometimes.

**Comment by miguelprada** [comment]
I believe all requests have been fulfilled.

**Comment by gavanderhoorn** [comment]
Thanks @miguelprada for the fix and for iterating on it with me. :+1:
